version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=hexa_user
      - POSTGRES_PASSWORD=hexa_pass
      - POSTGRES_DB=hexaguard
    ports:
      - "5435:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://hexa_user:hexa_pass@db:5432/hexaguard
      - REDIS_URL=redis://redis:6379/0
      - GROQ_API_KEY=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
      - OPENAI_API_KEY=tl-live-UhvRu1uKdp8ePwHiD31PfcsYySF0Cv7j
