"""create automated campaign tables

Revision ID: 237c8e1d5101
Revises: b4bfb79e4f47
Create Date: 2026-06-01 22:05:04.710961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237c8e1d5101'
down_revision: Union[str, Sequence[str], None] = 'b4bfb79e4f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('selected_models', sa.JSON(), nullable=False),
    sa.Column('selected_scenario_ids', sa.JSON(), nullable=False),
    sa.Column('selected_categories', sa.JSON(), nullable=False),
    sa.Column('selected_mutations', sa.JSON(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('completed_tests', sa.Integer(), nullable=False),
    sa.Column('failed_tests', sa.Integer(), nullable=False),
    sa.Column('critical_findings', sa.Integer(), nullable=False),
    sa.Column('average_risk_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_id'), 'campaigns', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('campaign_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_pk', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('scenario_pk', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.String(length=100), nullable=True),
    sa.Column('attack_name', sa.String(length=255), nullable=True),
    sa.Column('attack_category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('owasp_category', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('mutation_type', sa.String(length=100), nullable=False),
    sa.Column('input_prompt', sa.Text(), nullable=False),
    sa.Column('mutated_prompt', sa.Text(), nullable=False),
    sa.Column('sandbox_report', sa.JSON(), nullable=True),
    sa.Column('model_response', sa.JSON(), nullable=True),
    sa.Column('ai_evaluation', sa.JSON(), nullable=True),
    sa.Column('risk_assessment', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('final_status', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_pk'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_results_attack_category'), 'campaign_results', ['attack_category'], unique=False)
    op.create_index(op.f('ix_campaign_results_campaign_id'), 'campaign_results', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_results_campaign_pk'), 'campaign_results', ['campaign_pk'], unique=False)
    op.create_index(op.f('ix_campaign_results_final_status'), 'campaign_results', ['final_status'], unique=False)
    op.create_index(op.f('ix_campaign_results_id'), 'campaign_results', ['id'], unique=False)
    op.create_index(op.f('ix_campaign_results_model_name'), 'campaign_results', ['model_name'], unique=False)
    op.create_index(op.f('ix_campaign_results_owasp_category'), 'campaign_results', ['owasp_category'], unique=False)
    op.create_index(op.f('ix_campaign_results_scenario_id'), 'campaign_results', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_campaign_results_scenario_pk'), 'campaign_results', ['scenario_pk'], unique=False)
    op.create_index(op.f('ix_campaign_results_severity'), 'campaign_results', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_results_severity'), table_name='campaign_results')
    op.drop_index(op.f('ix_campaign_results_scenario_pk'), table_name='campaign_results')
    op.drop_index(op.f('ix_campaign_results_scenario_id'), table_name='campaign_results')
    op.drop_index(op.f('ix_campaign_results_owasp_category'), table_name='campaign_results')
    op.drop_index(op.f('ix_campaign_results_model_name'), table_name='campaign_results')
    op.drop_index(op.f('ix_campaign_results_id'), table_name='campaign_results')
    op.drop_index(op.f('ix_campaign_results_final_status'), table_name='campaign_results')
    op.drop_index(op.f('ix_campaign_results_campaign_pk'), table_name='campaign_results')
    op.drop_index(op.f('ix_campaign_results_campaign_id'), table_name='campaign_results')
    op.drop_index(op.f('ix_campaign_results_attack_category'), table_name='campaign_results')
    op.drop_table('campaign_results')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
