"""create attack_scenarios table

Revision ID: 988559150b8c
Revises: 
Create Date: 2026-06-01 14:42:09.095588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '988559150b8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.String(length=100), nullable=False),
    sa.Column('attack_name', sa.String(length=255), nullable=False),
    sa.Column('attack_category', sa.String(length=100), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('risk_goal', sa.Text(), nullable=False),
    sa.Column('expected_safe_behavior', sa.Text(), nullable=False),
    sa.Column('unsafe_behavior', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('owasp_category', sa.String(length=255), nullable=False),
    sa.Column('mitre_atlas_mapping', sa.String(length=255), nullable=True),
    sa.Column('requires_tool', sa.Boolean(), nullable=False),
    sa.Column('requires_rag', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('mutation_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('safe_for_demo', sa.Boolean(), nullable=False),
    sa.Column('dataset_version', sa.String(length=100), nullable=True),
    sa.Column('expected_label', sa.String(length=100), nullable=True),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_scenarios_attack_category'), 'attack_scenarios', ['attack_category'], unique=False)
    op.create_index(op.f('ix_attack_scenarios_id'), 'attack_scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_attack_scenarios_owasp_category'), 'attack_scenarios', ['owasp_category'], unique=False)
    op.create_index(op.f('ix_attack_scenarios_scenario_id'), 'attack_scenarios', ['scenario_id'], unique=True)
    op.create_index(op.f('ix_attack_scenarios_severity'), 'attack_scenarios', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attack_scenarios_severity'), table_name='attack_scenarios')
    op.drop_index(op.f('ix_attack_scenarios_scenario_id'), table_name='attack_scenarios')
    op.drop_index(op.f('ix_attack_scenarios_owasp_category'), table_name='attack_scenarios')
    op.drop_index(op.f('ix_attack_scenarios_id'), table_name='attack_scenarios')
    op.drop_index(op.f('ix_attack_scenarios_attack_category'), table_name='attack_scenarios')
    op.drop_table('attack_scenarios')
    # ### end Alembic commands ###
