"""add max tests to campaigns

Revision ID: 9ee188607774
Revises: eaf9ca72fd1e
Create Date: 2026-06-01 22:32:52.442759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ee188607774'
down_revision: Union[str, Sequence[str], None] = 'eaf9ca72fd1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('max_tests', sa.Integer(), server_default='20', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'max_tests')
    # ### end Alembic commands ###
