"""create manual red team runs table

Revision ID: b4bfb79e4f47
Revises: 988559150b8c
Create Date: 2026-06-01 17:03:29.814187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4bfb79e4f47'
down_revision: Union[str, Sequence[str], None] = '988559150b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_red_team_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_pk', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.String(length=100), nullable=True),
    sa.Column('attack_name', sa.String(length=255), nullable=True),
    sa.Column('attack_category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('owasp_category', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('original_prompt', sa.Text(), nullable=False),
    sa.Column('edited_prompt', sa.Text(), nullable=False),
    sa.Column('sandbox_report', sa.JSON(), nullable=True),
    sa.Column('model_response', sa.JSON(), nullable=True),
    sa.Column('ai_evaluation', sa.JSON(), nullable=True),
    sa.Column('risk_assessment', sa.JSON(), nullable=True),
    sa.Column('final_status', sa.String(length=100), nullable=True),
    sa.Column('human_verdict', sa.String(length=100), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_pk'], ['attack_scenarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_red_team_runs_attack_category'), 'manual_red_team_runs', ['attack_category'], unique=False)
    op.create_index(op.f('ix_manual_red_team_runs_human_verdict'), 'manual_red_team_runs', ['human_verdict'], unique=False)
    op.create_index(op.f('ix_manual_red_team_runs_id'), 'manual_red_team_runs', ['id'], unique=False)
    op.create_index(op.f('ix_manual_red_team_runs_model_name'), 'manual_red_team_runs', ['model_name'], unique=False)
    op.create_index(op.f('ix_manual_red_team_runs_owasp_category'), 'manual_red_team_runs', ['owasp_category'], unique=False)
    op.create_index(op.f('ix_manual_red_team_runs_scenario_id'), 'manual_red_team_runs', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_manual_red_team_runs_scenario_pk'), 'manual_red_team_runs', ['scenario_pk'], unique=False)
    op.create_index(op.f('ix_manual_red_team_runs_severity'), 'manual_red_team_runs', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_red_team_runs_severity'), table_name='manual_red_team_runs')
    op.drop_index(op.f('ix_manual_red_team_runs_scenario_pk'), table_name='manual_red_team_runs')
    op.drop_index(op.f('ix_manual_red_team_runs_scenario_id'), table_name='manual_red_team_runs')
    op.drop_index(op.f('ix_manual_red_team_runs_owasp_category'), table_name='manual_red_team_runs')
    op.drop_index(op.f('ix_manual_red_team_runs_model_name'), table_name='manual_red_team_runs')
    op.drop_index(op.f('ix_manual_red_team_runs_id'), table_name='manual_red_team_runs')
    op.drop_index(op.f('ix_manual_red_team_runs_human_verdict'), table_name='manual_red_team_runs')
    op.drop_index(op.f('ix_manual_red_team_runs_attack_category'), table_name='manual_red_team_runs')
    op.drop_table('manual_red_team_runs')
    # ### end Alembic commands ###
